apiVersion: v1
kind: Pod
metadata:
  labels:
  name: app
spec:
  containers:
  - image: registry.gitlab.com/personalgroub/neogym-html/neogym-html:v1
    name: app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
    - name: app-secret
